### ISSUE TITLE
Executing the injected file

### ISSUE THREAD

**Issue by hamzaaitbrik** [carlospuenteg/File-Injector#1]
Not an issue, more of a question. I would like to know if I store a Python script(or any script/app) in an image, upon opening that image, will that Python script be executed? I have tried doing so with no luck, and I would like to know have you thought about making this feature? If not, am I allowed to fork this repository and develop it in the upcoming days/weeks, also, any idea how to accomplish such thing? Thanks.

**Comment by carlospuenteg** [comment]
If you mean that when you preview the image, the file inside of it gets executed, I don't even think it's possible, but if you want to try, feel free to do it.
